// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_nr_cnpj");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_nm_contato");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_ds_email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_ds_ender");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_nm");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frn_nr_telefone");

                    b.HasKey("Id");

                    b.ToTable("tbfornecedor", (string)null);
                });

            modelBuilder.Entity("API.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mov_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mov_dh_data");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("mov_ds_observacao");

                    b.Property<int>("ProdutoVariacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("var_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("mov_nr_quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mov_tp_tipo");

                    b.HasKey("Id");

                    b.ToTable("tbmovimentacao_estoque", (string)null);
                });

            modelBuilder.Entity("API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ped_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ped_nm_cliente");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ped_dh_pedido");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ped_st_pedido");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("ped_vl_total");

                    b.HasKey("Id");

                    b.ToTable("tbpedido", (string)null);
                });

            modelBuilder.Entity("API.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("ped_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_nm_produto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("item_nr_quantidade");

                    b.Property<int?>("TamanhoId")
                        .HasColumnType("integer")
                        .HasColumnName("var_id");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("item_vl_unitario");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("tbpedido_item");
                });

            modelBuilder.Entity("API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prod_dh_cadastro");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prod_nm");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_id");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("TipoId");

                    b.ToTable("tbproduto", (string)null);
                });

            modelBuilder.Entity("API.Models.ProdutoVariacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("var_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("var_dh_cadastro");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("var_nr_quantidade");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("var_nm_tamanho");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("var_vl_compra");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("var_vl_venda");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("tbproduto_variacao", (string)null);
                });

            modelBuilder.Entity("API.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cd");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ds");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_nm");

                    b.HasKey("Id");

                    b.ToTable("tbtipo", (string)null);
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usu_dh_nascto");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_ds_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_nm");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_tp_role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_ds_senha");

                    b.Property<long?>("Telefone")
                        .HasColumnType("bigint")
                        .HasColumnName("usu_nr_telefone");

                    b.HasKey("Id");

                    b.ToTable("tbusuario", (string)null);
                });

            modelBuilder.Entity("API.Models.PedidoItem", b =>
                {
                    b.HasOne("API.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("API.Models.Produto", b =>
                {
                    b.HasOne("API.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("API.Models.ProdutoVariacao", b =>
                {
                    b.HasOne("API.Models.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("API.Models.Produto", b =>
                {
                    b.Navigation("Variacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
