services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: APDV-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: APDV
    ports:
      - "5490:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j-apdv
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  neo4j-cypher:
    image: neo4j:5
    container_name: neo4j-cypher-apdv
    restart: always
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_cypher_data:/data
      - neo4j_cypher_logs:/logs
      - neo4j_cypher_import:/var/lib/neo4j/import
      - neo4j_cypher_plugins:/plugins

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-apdv
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - pgvector
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apdv-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pgvector;Port=5432;Database=APDV;Username=admin;Password=admin
    ports:
      - "5145:80"
    depends_on:
      - pgvector
    volumes:
      - ./:/src

volumes:
  pgvector_data:
  pgadmin_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  neo4j_cypher_data:
  neo4j_cypher_logs:
  neo4j_cypher_import:
  neo4j_cypher_plugins: